services:
  - type: web
    name: portfolio-frontend
    runtime: static
    buildCommand: null
    staticPublishPath: ./
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache

  - type: web
    name: portfolio-backend
    runtime: nodejs
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString

databases:
  - name: portfolio-db
    plan: free
    ipAllowList: []